version: "3"

services:
    django:
        build:
            context: .
        image: docker_tutorial_django
        stdin_open: true
        tty: true
        ports: 
            - 8000:8000
        environment: 
            - TZ=Asia/Seoul
            - DATABASE_URL=mysql://root:mysqlroot@db:3306/db
        command: >
            bash -c "
            chmod +x ./wait-for-it.sh
            && ./wait-for-it.sh db:5432 -t 10
            && python manage.py makemigrations
            && python manage.py migrate
            && python manage.py runserver 0.0.0.0:8000"
    
    db:
        image: postgres
        ports:
            - 5432:5432
        environment: 
            - TZ=Asia/Seoul
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        restart: always

    chrome:
        image: selenium/standalone-chrome
        expose:
            - 4444